version: '3.4'

services:
  catalogdb.mongodb:
    container_name: catalogdb.mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  basketdb.redis:
    container_name: basketdb.redis
    restart: always
    ports:
      - "6379:6379"
        
  discountdb.postgres:
    container_name: discountdb.postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=discountdb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_discount:/var/lib/postgresql/data/

  orderdb.postgres:
    container_name: orderdb.postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=orderdb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_order:/var/lib/postgresql/data/
  
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  
  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8080"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb.mongodb:27017"
    depends_on:
     - catalogdb.mongodb
    ports:
      - "8000:80"

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb.redis:6379"
      - "GrpcSettings:DiscountUrl=http://discount.grpc"
    depends_on:
      - basketdb.redis
    ports:
      - "8001:80"
        
  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb.postgres;Port=5432;Database=discountdb;User Id=admin;Password=admin;"
    depends_on:
      - discountdb.postgres
    ports:
      - "8002:80"

  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb.postgres;Port=5432;Database=discountdb;User Id=admin;Password=admin;"
    depends_on:
      - discountdb.postgres
    ports:
      - "8003:80"

  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderingConnectionString=Server=orderdb.sqlserver;Database=OrderDb;User Id=sa;Password=password1234567890;"
    depends_on:
      - orderdb.sqlserver
    ports:
      - "8004:80"

